language: node_js
cache: yarn
before_script:
  - psql -c 'create database webmention_test;' -U postgres
sudo: false
matrix:
  include:
    - node_js: "10"
      addons:
        postgresql: "9.4"
    - node_js: "8"
      addons:
        postgresql: "9.4"
    - node_js: "8"
      addons:
        postgresql: "9.3"
after_success:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
